### ISSUE TITLE
A question about data preprocessing

### ISSUE THREAD

**Issue by Zhangyunyan77** [qolina/NNED#1]
Thank you for the project. I have some problems in data preprocessing of ACE05. Using your data, I can get the best 62% F1 for bilstm model.  Would you please upload Feng data and liqi data? Or tell me the differences of data preprocessing between those data?

**Comment by qolina** [comment]
Hi. Thanks for attention. Actually, I only have permission to use their data instead of release them. And I am not sure about details of data processing. You can ask them for the data. My data processing conduct very fundamental sentence splitting and tokenization. I suppose it matters a lot. 
By the way, (Miwa et. al, 2016) published ACE 05 data processing for RE. You can refer to that. Ref: https://github.com/tticoin/LSTM-ER/

**Comment by Zhangyunyan77** [comment]
Thanks a lot. And whom should I ask for the data? Is Feng data from A Language-Independent Neural Network for Event Detection? Is liqi data from Joint Event Extraction via Structured Prediction with Global Features?

**Comment by qolina** [comment]
Yes, both are correct.

**Comment by Zhangyunyan77** [comment]
Thank you!

**Comment by zhj96** [comment]
> Thank you!

Hi,do you konw how to preprocess ace dataset now？I processed it by myself,it proforms badly,if you know how to process it,could you share it to me,thanks！
